### ISSUE TITLE
error thrown when sshing for jupyter

### ISSUE THREAD

**Issue by samuel100** [Azure/thunderbolt#107]
Trying to get Jupyter up-and-running.... come across the following error:

![image](https://user-images.githubusercontent.com/9161628/30917138-2b90b870-a393-11e7-8254-95597aa661c8.png)

**Comment by paselem** [comment]
Hi @samuel100,
Looks like you're on Windows. Are you using an ssh-friendly shell (like the Ubuntu Bash or Git Shell)? I think the issue may be it's looking for your ssh public key and not finding it. If you are using a standard Windows command prompt, you can try switching off the sshkey in your secrets.yaml file and use a password instead

**Comment by timotheeguerin** [comment]
I think it just cannot find the ssh executable. Does typing ssh in the console do anything for you? Otherwise as @paselem mentioned you can use the ubuntu bash or git shell. You can also install git and select the field to add the executables to the path which should allow you to use ssh from everywhere

**Comment by samuel100** [comment]
I am in windows cmd prompt. My workaround is to set connect=False .... this gives me the ssh command, which means I can use putty to ssh in. Will use the Ubuntu bash going forward
