### ISSUE TITLE
IDs should be declared as a param (and not in cluster.yaml)

### ISSUE THREAD

**Issue by jiata** [Azure/thunderbolt#117]
I remember we chatted about enforcing that people set their cluster id as a param, and not a config

https://github.com/Azure/thunderbolt/blob/master/dtde/config.py#L176
https://github.com/Azure/thunderbolt/blob/master/config/cluster.yaml#L4

not sure if there are other places that this needs to be updated.

**Comment by jiata** [comment]
Looks like it's partially addressed here: #112

**Comment by jafreck** [comment]
Yeah, #112 removes ID as default. What are you looking for in regards to that first link in config.py?

That message is displayed when id is not present as a command line parameter or in the cluster.yaml, so it alerts the user to set the id in one of those two places. Should I just reverse the order so that passing it as a parameter is the first suggestion?

**Comment by jiata** [comment]
i think it should only suggest it as a param, I remember we chatted about enforcing that people set their cluster id as a param, and not a config.

**Comment by jafreck** [comment]
Okay, sounds good -- i'll update the message to reflect that.

As of now, we do still support passing id in the config file though. I think we concluded that we should encourage passing as parameter, and have that be the default experience, but leave passing an id in the config file as an option for users. There wasn't a good reason to remove that functionality entirely.
