### ISSUE TITLE
sshkey not working from config when using the ssh cmd

### ISSUE THREAD

**Issue by jiata** [Azure/thunderbolt#99]
When I run `azb spark cluster create --id test` by default it should create the cluster, wait, and then create the user for the cluster (with the specified SSH_key)

However, this is broken today. After waiting for the cluster to spin up, i should be able to run `azb spark cluster ssh --id test`, and it should just use the ssh key. Instead, i get prompted with inputing a password.

This makes me think that creating the cluster with the user did not work properly.

**Comment by jafreck** [comment]
I could not reproduce this. Did you set the ssh_pub_key variable in secrets.yaml?

**Comment by jiata** [comment]
@jafreck yep i did

**Comment by jafreck** [comment]
Looking into it a little deeper, it looks like this issue is resulting from custom names for ssh keys. If your private key is in a location or has a name other than one automatically checked by the ssh client, then the client will not pick it up. This means that even though the user is created with the public key given, connecting will not work.

The solution to this on the command line is to add a `-i <path/to/identity/file>` flag. We can add support for this by allowing users to specify the path and name of their private key in the secrets.yaml file. We would just need to add a ssh-priv-key field.
